### ISSUE TITLE
Remove `size` from messgen header

### ISSUE THREAD

**Issue by Roman-** [microavia/messgen#49]
The 4-byte `size` field in messages header is redundant and could be eliminated.
For messages without dynamic fields, size is known in beforehand.
For dynamic messages, the minimum static size is also known in beforehand, and the size of every dynamic filed is contained within the message payload.

**Comment by Zemledelec** [comment]
Might be the reason why header size exists is that we could check the message is valid.

**Comment by Roman-** [comment]
Discussed this with @DrTon. The reason to have `size` in header is to be able to skip new messages that the receiver doesn't have in his protocol yet.
